### ISSUE TITLE
Keybindings not working when controls are hidden

### ISSUE THREAD

**Issue by Creatium** [zakjan/mapbox-gl-draw-geodesic#9] opened 2021-05-26 08:38 UTC
Hi,

I'm trying to implement a custom UI for drawing tools and so I want to hide default control buttons. I can do that with 

`displayControlsDefault: false`

but then i.e. deletion of polygon is not working. If I add a polygon, select it and press DEL button on my keyboard, nothing happens. Deletion only works when Trash button is present in controls.

`keybindings: true` ir set.

**Comment by zakjan** [comment] 2021-05-28 12:34
Hi @Creatium could you verify if this is really an issue of this plugin, or mapbox-gl-draw? This plugin doesn't override anything related with keyboard bindings, I'm not sure what could be wrong on this side.

**Comment by zakjan** [comment] 2022-01-23 21:16
Closing, can't reproduce.

**Closed by zakjan** 2022-01-23 21:16 UTC
