### ISSUE TITLE
Issue with new release 2.2.x :  Import "enable" will always be undefined because the file "node_modules/mapbox-gl-draw-geodesic/dist/mapbox-gl-draw-geodesic.umd.min.js" has no exports [import-is-undefined]

### ISSUE THREAD

**Issue by jules-w2** [zakjan/mapbox-gl-draw-geodesic#25] opened 2023-10-02 13:26 UTC
Hey

They have an issue with the new release 2.2x...
If i rollback to the 2.1.3.. all is working fine.

Do yo understand what's the problem ? Can you solve this issue ? 

```
▲ [WARNING] Import "enable" will always be undefined because the file "node_modules/mapbox-gl-draw-geodesic/dist/mapbox-gl-draw-geodesic.umd.min.js" has no exports [import-is-undefined]
```

 ```js
#  app/javascript/search.js:962:39:
 modes   = MapboxDrawGeodesic.enable(modes)
  ```

in chrome console :
```
Uncaught TypeError: (void 0) is not a function
```

**Comment by zakjan** [comment] 2023-10-02 13:53
@jules-w2 Hi, what's your bundler or framework? How do you import the library? It seems that the issue is that your bundler loads UMD build instead of CJS or ESM.

**Comment by jules-w2** [comment] 2023-10-02 14:36
hey @zakjan 

we work on Ruby on rails 7.x and Esbuild  [esbuild](https://esbuild.github.io/) for build js assets

here en extrait of my package.json.

Do you have a solution for us ? 


```json
{
  "name":            "...",
  "private":         true,
  "version":         "0.1.0",
  "dependencies": {
    "@mapbox/mapbox-gl-draw":         "^1.4.3",
    "@mapbox/mapbox-gl-geocoder":     "^5.0.1",
    "@rails/ujs":                     "^7.0.8",
    "@turf/turf":                     "^6.5.0",
    "esbuild":                        "^0.19.4",
    "mapbox-gl":                      "^2.15.0",
    "mapbox-gl-draw-geodesic":        "^2.2.1"},
    "scripts": {
    "build":         "esbuild app/javascript/*.* --bundle  --outdir=app/assets/builds --minify",
    "build-dev":     "esbuild app/javascript/*.* --bundle  --outdir=app/assets/builds --sourcemap"
    }
```    

```javascript
import mapboxgl                 from "mapbox-gl"
import MapboxDraw               from "@mapbox/mapbox-gl-draw"
import MapboxGeocoder           from "@mapbox/mapbox-gl-geocoder"
import * as MapboxDrawGeodesic  from "mapbox-gl-draw-geodesic"
import * as turf                from "@turf/turf"

....
const draw = new MapboxDraw({
      boxSelect:   false,
      modes:       MapboxDrawGeodesic.enable(MapboxDraw.modes),
      clickBuffer: 4
      ....
```

Bests

**Comment by jaybo** [comment] 2023-10-02 20:27
Same problem here:

` App •  WARNING  •  UI  in ./src/modules/DZMap.ts`
`export 'enable' (imported as 'MapboxDrawGeodesic') was not found in 'mapbox-gl-draw-geodesic' (module has no exports)`

```
yarn add mapbox-gl-draw-geodesic

//@ts-ignore
import * as MapboxDrawGeodesic from "mapbox-gl-draw-geodesic";
...
// Add static mode
let modes = MapboxDraw.modes;
modes = MapboxDrawGeodesic.enable(modes);
modes = MapboxDrawWaypoint.enable(modes);
```

Note that previous to V2.2.x I had to use //@ts-ignore to avoid whatever Typescript didn't like about the import, but it did not give the above warning during compilation and everything ran successfully.

Now with 2.2.x it errors at runtime with 
`DynamicLogs.ts:75 DZMap init ERROR: TypeError: mapbox_gl_draw_geodesic__WEBPACK_IMPORTED_MODULE_5__.enable is not a function`

**Comment by zakjan** [comment] 2023-10-02 21:20
Thank you both, the issue was in missing ESM exports for `"type": "module"`. I have published 2.2.3, could you try it now, please?

**Comment by jules-w2** [comment] 2023-10-02 21:53
I  have a new error with this release.

```bash
$ esbuild app/javascript/*.* --bundle  --outdir=app/assets/builds --sourcemap --watch
✘ [ERROR] Could not resolve "@mapbox/mapbox-gl-draw/src/constants.js"
    node_modules/mapbox-gl-draw-geodesic/dist/mapbox-gl-draw-geodesic.esm.js:1:84:
      1 │ ..., cursors, events } from '@mapbox/mapbox-gl-draw/src/constants.js';
        ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  You can mark the path "@mapbox/mapbox-gl-draw/src/constants.js" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
✘ [ERROR] Could not resolve "@mapbox/mapbox-gl-draw/src/lib/create_vertex.js"
    node_modules/mapbox-gl-draw-geodesic/dist/mapbox-gl-draw-geodesic.esm.js:2:25:
      2 │ ...reateVertex from '@mapbox/mapbox-gl-draw/src/lib/create_vertex.js';
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  You can mark the path "@mapbox/mapbox-gl-draw/src/lib/create_vertex.js" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
✘ [ERROR] Could not resolve "@mapbox/mapbox-gl-draw/src/lib/common_selectors.js"
    node_modules/mapbox-gl-draw-geodesic/dist/mapbox-gl-draw-geodesic.esm.js:6:33:
      6 │ ...electors from '@mapbox/mapbox-gl-draw/src/lib/common_selectors.js';
        ╵                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  You can mark the path "@mapbox/mapbox-gl-draw/src/lib/common_selectors.js" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
✘ [ERROR] Could not resolve "@mapbox/mapbox-gl-draw/src/lib/double_click_zoom.js"
    node_modules/mapbox-gl-draw-geodesic/dist/mapbox-gl-draw-geodesic.esm.js:7:28:
      7 │ ...ickZoom from '@mapbox/mapbox-gl-draw/src/lib/double_click_zoom.js';
        ╵                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  You can mark the path "@mapbox/mapbox-gl-draw/src/lib/double_click_zoom.js" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
  ```

**Comment by zakjan** [comment] 2023-10-02 21:56
@jules-w2 Right, this is because you use an incompatible version of `@mapbox/mapbox-gl-draw` 1.4. The latest compatible is 1.3.0 as of now, due to that 1.4.0 has removed source files that `mapbox-gl-draw-geodesic` depend on.

Upgrading to 1.4 is tracked separately at https://github.com/zakjan/mapbox-gl-draw-geodesic/pull/24.

**Comment by jules-w2** [comment] 2023-10-02 22:17
@zakjan 

Your version 2.1.3 is compatible with @mapbox/mapbox-gl-draw 1.4.3.

with this config is working fine. Do you know why the 2.2.x is not compatible ?

```json
{
  "name":            "...",
  "private":         true,
  "version":         "0.1.0",
  "dependencies": {
    "@mapbox/mapbox-gl-draw":         "^1.4.3",
    "@mapbox/mapbox-gl-geocoder":     "^5.0.1",
    "@rails/ujs":                     "^7.0.8",
    "@turf/turf":                     "^6.5.0",
    "esbuild":                        "^0.19.4",
    "mapbox-gl":                      "^2.15.0",
    "mapbox-gl-draw-geodesic":        "2.1.3"},
    "scripts": {
    "build":         "esbuild app/javascript/*.* --bundle  --outdir=app/assets/builds --minify",
    "build-dev":     "esbuild app/javascript/*.* --bundle  --outdir=app/assets/builds --sourcemap"
    }
  ```
  
I see in their changelog (https://github.com/mapbox/mapbox-gl-draw/blob/main/CHANGELOG.md#140), they have removed some libs. maybe you could add the dependencies you need in your module?
  
```bash
  "@mapbox/mapbox-gl-draw@^1.3.0":
  version "1.4.2"
  resolved "https://registry.npmjs.org/@mapbox/mapbox-gl-draw/-/mapbox-gl-draw-1.4.2.tgz"
  integrity sha512-Zvl5YN+tIuYZlzPmuzOgkoJsZX6sHMQsnFI+O3ox8EwYkpLO2w0U2FvVhQuVnq1Yys12x6UnF+0IPoEdBy2UfA==
  dependencies:
    "@mapbox/geojson-area" "^0.2.2"
    "@mapbox/geojson-extent" "^1.0.1"
    "@mapbox/geojson-normalize" "^0.0.1"
    "@mapbox/point-geometry" "^0.1.0"
    hat "0.0.3"
    lodash.isequal "^4.5.0"
    xtend "^4.0.2"
 ```

**Comment by jules-w2** [comment] 2023-10-04 14:23
@zakjan,

but I don't understand why your version 2.1.3 works fine with mapbox updates and your 2.2.x doesn't work.
I kept version 2.1.3 for the moment to be up to date on mapbox.

do you think your next release will be compatible with mapbox updates?

**Comment by zakjan** [comment] 2023-10-04 14:49
Because the build process has changed to support ESM. Previously, only the full UMD build was published, which bundles the sources of `mapbox-gl-draw` during the build.

Can you test whether it works for you with `mapbox-gl-draw` 1.3.0, please? If yes, we can close this.

Update to `mapbox-gl-draw` 1.4 is tracked separately in https://github.com/zakjan/mapbox-gl-draw-geodesic/pull/24. Yes, it will be supported one day, but I can't give a timeline, I'm busy with personal issues. I'm happy to accept a PR. The original PR from another contributor is incomplete.

**Comment by jaybo** [comment] 2023-10-04 16:50
Yes, v1.3.0 `mapbox-gl-draw` works with v2.2.3 `mapbox-gl-draw-geodesic` for me.

**Comment by jules-w2** [comment] 2023-10-04 17:05
@zakjan,

I tested it and yes your v 2.3.3 works with the old `mapbox-gl-draw` 1.3.0

**Comment by zakjan** [comment] 2023-10-04 17:08
Thank you. One step at a time.

**Closed by zakjan** 2023-10-04 17:08 UTC

**Comment by zakjan** [comment] 2023-10-05 21:34
@jules-w2 Could you try out 2.2.4, please? I've tried to solve the runtime compatibility with `mapbox-gl-draw` 1.4 by bundling 1.3 sources.

**Comment by jules-w2** [comment] 2023-10-05 23:09
Hey @zakjan 

it's not working.. :(

```json
  "dependencies": {
    "@mapbox/mapbox-gl-draw":         "^1.4.3",
    "@mapbox/mapbox-gl-geocoder":     "^5.0.1",
    "@rails/ujs":                     "^7.1.0",
    "@turf/turf":                     "^6.5.0",
    "mapbox-gl":                      "^2.15.0",
    "mapbox-gl-draw-geodesic":        "2.2.4"
  }
```

```bash
$ esbuild app/javascript/*.* --bundle  --outdir=app/assets/builds --sourcemap --watch
✘ [ERROR] Could not resolve "@mapbox/mapbox-gl-draw/src/constants.js"
18:05:12 js.1      |
    node_modules/mapbox-gl-draw-geodesic/dist/mapbox-gl-draw-geodesic.esm.js:1:84:
      1 │ ..., cursors, events } from '@mapbox/mapbox-gl-draw/src/constants.js';
        ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18:05:12 js.1      |
  You can mark the path "@mapbox/mapbox-gl-draw/src/constants.js" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
18:05:12 js.1      |
✘ [ERROR] Could not resolve "@mapbox/mapbox-gl-draw/src/lib/create_vertex.js"
18:05:12 js.1      |
    node_modules/mapbox-gl-draw-geodesic/dist/mapbox-gl-draw-geodesic.esm.js:2:25:
      2 │ ...reateVertex from '@mapbox/mapbox-gl-draw/src/lib/create_vertex.js';
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18:05:12 js.1      |
  You can mark the path "@mapbox/mapbox-gl-draw/src/lib/create_vertex.js" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
18:05:12 js.1      |
✘ [ERROR] Could not resolve "@mapbox/mapbox-gl-draw/src/lib/common_selectors.js"
18:05:12 js.1      |
    node_modules/mapbox-gl-draw-geodesic/dist/mapbox-gl-draw-geodesic.esm.js:6:33:
      6 │ ...electors from '@mapbox/mapbox-gl-draw/src/lib/common_selectors.js';
        ╵                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18:05:12 js.1      |
  You can mark the path "@mapbox/mapbox-gl-draw/src/lib/common_selectors.js" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
18:05:12 js.1      |
✘ [ERROR] Could not resolve "@mapbox/mapbox-gl-draw/src/lib/double_click_zoom.js"
18:05:12 js.1      |
    node_modules/mapbox-gl-draw-geodesic/dist/mapbox-gl-draw-geodesic.esm.js:7:28:
      7 │ ...ickZoom from '@mapbox/mapbox-gl-draw/src/lib/double_click_zoom.js';
        ╵                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18:05:12 js.1      |
  You can mark the path "@mapbox/mapbox-gl-draw/src/lib/double_click_zoom.js" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
```

**Comment by zakjan** [comment] 2023-10-06 05:37
@jules-w2 Ok, I'm sorry, I've used incorrect Rollup resolveOnly pattern. Try out 2.2.5, please.

**Comment by jules-w2** [comment] 2023-10-06 12:36
I confirm, it's working!!!! 
your 2.2.5 is compatible with  @mapbox/mapbox-gl-draw 1.4.x

thanks a lot @zakjan
